### ISSUE TITLE
Password handling

### ISSUE THREAD

**Issue by blacs30** [ajrosen/Bitwarden-Accelerator#10]
I have switched back to your workflow. Impressive jq work undearneath !
I enabled debug mode and saw my Bitwarden password.
It would be great if the Bitwarden masterpassword as well as the yubikey otp (if used) is not passed around but used directly.
Reduces the attack surface and gives little bit more peace of mind IMO.

**Comment by ajrosen** [comment]
The values are only visible in Alfred's debugger (or log file if the workflow's DEBUG variable is 1).  It won't take too much to keep them hidden.

And thanks, I love jq :)

**Comment by ajrosen** [comment]
Addressed in Release 4.1.2 #11
