### ISSUE TITLE
Firefox Developer Edition

### ISSUE THREAD

**Issue by waynehoover** [ajrosen/Bitwarden-Accelerator#12]
Thanks for a great workflow! Is it possible to have it work with Firefox Developer Edition too?

**Comment by ajrosen** [comment]
Fixed in release [4.2.0](https://github.com/ajrosen/Bitwarden-Accelerator/releases/tag/bwa-4.2.0)

**Comment by waynehoover** [comment]
I just upgraded, but I don't think it's working, I looked at the commit and didn't notice anything specifically related to FF Dev Edition in it: https://github.com/ajrosen/Bitwarden-Accelerator/commit/9f4893a77324b950dda5c6872836702a38b6865a

**Comment by ajrosen** [comment]
It won't show up in the source in the repository, except for a new icon (icons/org.mozilla.firefoxdeveloperedition.png).  The functional change is in _info.plist_, which is included in the exported workflow, but not in the repo.

Have you installed the [Alfred Integration extension](https://addons.mozilla.org/en-US/firefox/addon/alfred-launcher-integration) and [alfred-firefox workflow](https://github.com/deanishe/alfred-firefox/releases/latest)?

**Comment by waynehoover** [comment]
Actually, yes it does work. I thought it would work when I pulled up alfred and typed the `bw` but I see it's setup to search the current tab when I invoke it from the hotkey. It would be nice if it searched the current tab when I invoked it via the keyword also.

Again great workflow, it saves me tons of time.

**Comment by ajrosen** [comment]
Are you typing `bw` or `.bw`?  `bw<return>` gets the desired behavior.  `.bw` does not call the browser detection stuff.  It's actually that `bw` (and the hotkey) do the browser detection, and then call `.bw`.

Can you change your muscle memory to type `bw<return>` instead?  Changing the workflow would be...difficult.

**Comment by waynehoover** [comment]
Thanks for the explanation, I'll try and just use the hotkey when I want a password while I'm using my browser.
