### ISSUE TITLE
Session Expires after ~ 1 day

### ISSUE THREAD

**Issue by tardoe** [ajrosen/Bitwarden-Accelerator#18]
I am finding that I'm having to login every day and unlock the vault, even when using API Key-based authentication. Is is possible for the session to be kept open for a configurable length of time? This would be similar to how the BW desktop app and browser plugins function.

**Comment by ajrosen** [comment]
Someone else asked about this [quite recently](https://github.com/ajrosen/Bitwarden-Accelerator/discussions/16).

There's no session timeout, but I think sometimes the bw serve process terminates (crashes). If/when it does you're logged out of Bitwarden. The workflow uses it as a cache, and as a proxy for Bitwarden's API. It doesn't have any options.
