### ISSUE TITLE
Can't search my vault

### ISSUE THREAD

**Issue by Anber55** [ajrosen/Bitwarden-Accelerator#22]
Hello, I have a problem, your Workflow works very well, but I may have a little problem that I need you to help me solve!
I've set up all the settings and it works fine, but I can search my folders and it shows up correctly, but I can't search my vaults, i.e. I can't search for specific individual passwords, so please help me out, thanks!

<img width="633" alt="截屏2024-09-24 12 08 52" src="https://github.com/user-attachments/assets/114d5f88-81e1-4743-b7c9-18153d7148fd">

![截屏2024-09-24 12 08 36](https://github.com/user-attachments/assets/5390828c-2447-4457-9032-3819ead0b0d3)

**Comment by ajrosen** [comment]
I think there was something off about the .workflow file I attached to the 6.1.1 release.

Could you try [6.1.2](https://github.com/ajrosen/Bitwarden-Accelerator/releases/download/bwa-6.1.2/Bitwarden.Accelerator.alfredworkflow) which I just pushed?

Thanks!

**Comment by Anber55** [comment]
Already good, thanks, is this Alfred secure? Does it affect the security of Bitwarden passwords, just want to know, thanks!

**Comment by ajrosen** [comment]
I'm not sure what you mean by "Alfred secure"?

It does not affect the security of your passwords.  When the workflow caches data from your vault (saves some of it to disk), it first removes sensitive fields.

Logins:
- password
- totp
- passwordHistory

Cards:
- number
- code
