### ISSUE TITLE
Get value from additional fields

### ISSUE THREAD

**Issue by blacs30** [ajrosen/Bitwarden-Accelerator#6]
Thanks for this workflow which has already so many great features.

Often I use additional fields to place information I'd like to access.
Currently it seems not to be possible with this workflow.
Would be super helpful if that could be made possible.
Maybe I'm using Bitwarden little wrong but I prefer to have 1 entry for website x that has everything in it (except for OTP and recovery codes, that's a risk to place them next to the password and the username IMO)

**Comment by ajrosen** [comment]
I'm curious to understand your use case.  Are you talking about **custom fields**?  Or putting multiple username/password pairs in a single item?

The Function modifier brings up a persistent dialog with all fields, including custom fields, that you can copy/paste from.

I agree that having OTP codes in the same store as the passwords defeats the **_M_** of **MFA**.

**Comment by ajrosen** [comment]
Ahh, now I get why your workfow's "show all fields" option shows them in Alfred.

I think that adding _Cmd-Opt_ to do it that way, and keeping _Fn_ to show a dialog, would be a very nice addition.

**Comment by ajrosen** [comment]
Added in [version 4.0.0](https://github.com/ajrosen/Bitwarden-Accelerator/releases/tag/bwa-4.0.0).

Thanks!
